### ISSUE TITLE
Canvas LMS returning error 422 Unprocessable Entity

### ISSUE THREAD

**Issue by jeffmiko** [celtic-project/LTI-PHP#11] opened 2020-07-14 16:42 UTC
It was fairly easy to get my LTI 1.3 app working with Moodle using your Rating app example as a guide (thanks!). I can't seem to get the Rating app or my app to work with Canvas LMS. It has something to do with the authorization piece. I get an HTTP 422 Unprocessable Entity error during the authorization process. I can't get the Rating app to work with Canvas either. It encounters the same 422 error. Any thoughts? 

Canvas loads my connect.php into an iframe with this request payload:
```
{
"iss":"http://www.canvasvm.local",
"login_hint":"314f5492a2603d07aec9264e40c827b9f302667d",
"client_id":"10000000000006",
"target_link_uri":"http://myapp.local/lti/myapp/connect.php",
"lti_message_hint":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllciI6ImY3NDUzOTgyYzkyYzkyNmI0MmU3YzAzMDdmMGI5MzhiMGM3NzljMGIwMzAyNTU5OTFkMWZmYWE3OWEwMzZlN2ZjZGYyNjE0OGI0NTFiMjU1NmYyMjM3Mjg0ZmJlODljMThhNWRmMjU1YTM1ZTgxZmE3ZjZlMTFlYjhiYjBiOTllIiwiY2FudmFzX2RvbWFpbiI6ImNhbnZhc3ZtLmxvY2FsIiwiY29udGV4dF90eXBlIjoiQ291cnNlIiwiY29udGV4dF9pZCI6MTAwMDAwMDAwMDAwMDEsImV4cCI6MTU5NDcyNjE2Mn0.AUUZxi66t3oxwMwFlrWJ951vruaxefn6ajf7T9lAvlI",
"canvas_region":"not_configured"
}
```

Then I see my connect.php make a call to http://www.canvasvm.local/api/lti/authorize which fails with a 422 error. This is the payload the connect.php sent:
```
{
"client_id":"10000000000006",
"login_hint":"314f5492a2603d07aec9264e40c827b9f302667d",
"nonce":"Zo0i1KY3rJ7N6fbBqOgHkrEPKDmSaDLI",
"prompt":"none",
"redirect_uri":"http://myapp.local/lti/myapp/connect.php",
"response_mode":"form_post",
"response_type":"id_token",
"scope":"openid",
"state":"F9MuZleZ",
"lti_message_hint":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllciI6ImY3NDUzOTgyYzkyYzkyNmI0MmU3YzAzMDdmMGI5MzhiMGM3NzljMGIwMzAyNTU5OTFkMWZmYWE3OWEwMzZlN2ZjZGYyNjE0OGI0NTFiMjU1NmYyMjM3Mjg0ZmJlODljMThhNWRmMjU1YTM1ZTgxZmE3ZjZlMTFlYjhiYjBiOTllIiwiY2FudmFzX2RvbWFpbiI6ImNhbnZhc3ZtLmxvY2FsIiwiY29udGV4dF90eXBlIjoiQ291cnNlIiwiY29udGV4dF9pZCI6MTAwMDAwMDAwMDAwMDEsImV4cCI6MTU5NDcyNjE2Mn0.AUUZxi66t3oxwMwFlrWJ951vruaxefn6ajf7T9lAvlI"
}
```

It looks like the Tool->result function outputs this in the iframe which generates the 422 error
```
<html>
<head>
<title>IMS LTI message</title>
<script type="text/javascript">
//<![CDATA[
function doOnLoad() {
    document.forms[0].submit();
}

window.onload=doOnLoad;
//]]>
</script>
</head>
<body>
<form action="http://www.canvasvm.local/api/lti/authorize" method="post" target="" encType="application/x-www-form-urlencoded">
    <input type="hidden" name="client_id" value="10000000000006" />
    <input type="hidden" name="login_hint" value="314f5492a2603d07aec9264e40c827b9f302667d" />
    <input type="hidden" name="nonce" value="bUrPzbOLFeTXvMv25VP9zjevCteSEAO2" />
    <input type="hidden" name="prompt" value="none" />
    <input type="hidden" name="redirect_uri" value="http://myapp.local/lti/myapp/connect.php" />
    <input type="hidden" name="response_mode" value="form_post" />
    <input type="hidden" name="response_type" value="id_token" />
    <input type="hidden" name="scope" value="openid" />
    <input type="hidden" name="state" value="5Yi1u3sN" />
    <input type="hidden" name="lti_message_hint" value="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXJpZmllciI6IjNiZTY5YzUxZWE0ODg3OGFlNjEzMGZmYjkzNDIyNWIxMzM4MmQ4YzJkOTRkZjkyMmY1YThhYjEyMTQzZWMwNDI2NDhkZmNjZGU0N2E5MjM0ZDY3MmI4ODM3MDVhNjljYWYxMWY3ZmVhN2JhOWE1NzVlNjA1YTFjYTQwZjgzOWJjIiwiY2FudmFzX2RvbWFpbiI6ImNhbnZhc3ZtLmxvY2FsIiwiY29udGV4dF90eXBlIjoiQ291cnNlIiwiY29udGV4dF9pZCI6MTAwMDAwMDAwMDAwMDEsImV4cCI6MTU5NDc0MTQwNn0.EZYcc7gNnAPaSCcQkXZ9r7So5ZeGKkrLA6324dWUr5M" />
</form>
</body>
</html>
```

I am using LTI-PHP 4.0.1
I am using a Bitnami install of Canvas using the June code.
I have my app setup as an LTI 1.3 app in Canvas (developer LTI key and App)
My canvas host is www.canvasvm.local

**Comment by spvickers** [comment] 2020-07-17 15:20
What version of PHP are you running the Rating app on?

**Comment by spvickers** [comment] 2020-07-17 21:27
I have been unable to replicate your HTTP 422 response in Canvas (or Moodle) but I have found that Canvas is returning the fully-qualified context type which is too long for the database field.  I will fix this in the next release, but in the meantime, try increasing the size of the type field in the lti2_context table to 100 (or at least 60) characters.

**Comment by jeffmiko** [comment] 2020-07-17 22:13
I am using NGINX with PHP 7.3.19. I can get LTI 1.1 working in Canvas just not 1.3. Using LTI 1.3 it's not inserting any records into the lti2_context table. I don't think it's making it that far as it's getting the 422 error from the Canvas LMS before it gets to that point. I did increase the field size anyway but it made no difference. It could be my Canvas setup using Bitnami installer. I have another Canvas instance that has 3 other LTI 1.3 apps working. I will try the Rating app on that instance.

**Comment by spvickers** [comment] 2020-07-22 10:48
Closing this issue for now.  Please update this issue if your problem persists and you think it is being caused by this library.  Thanks.

**Closed by spvickers** 2020-07-22 10:48 UTC
