### ISSUE TITLE
Fatal error: Uncaught TypeError: ceLTIc\LTI\ResourceLink::domnodeToArray(): Argument #1 ($node) 

### ISSUE THREAD

**Issue by Gnastw** [celtic-project/LTI-PHP#82] opened 2024-07-16 13:55 UTC
Hello,

We have encounter a new bug while trying to do $resourceLink->doOutcomesService(ServiceAction::Write, $outcome, $user);

We got the message : Fatal error: Uncaught TypeError: ceLTIc\LTI\ResourceLink::domnodeToArray(): Argument #1 ($node) must be of type object, null given, called in .../vendor/celtic/lti/src/ResourceLink.php on line 1608

We also have this warning : 
Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in .../vendor/celtic/lti/src/ResourceLink.php on line 1607

**Comment by spvickers** [comment] 2024-07-16 20:39
Thanks for reporting this.  I am in the middle if tightening up the data checking of responses to service requests, including this example, and hope to have an update committed within the next week.  For all cases, the cause will be an improperly formatted response being received.

**Comment by spvickers** [comment] 2024-08-30 14:31
This issue should have been resolved by the latest release (5.1.0).

**Closed by spvickers** 2024-08-30 14:31 UTC
