### ISSUE TITLE
Sending outcome to Moodle - token issue

### ISSUE THREAD

**Issue by onebonsai** [celtic-project/LTI-PHP#93] opened 2024-11-07 21:04 UTC
Hi,

I am trying to integrate with Moodle, and am getting an error back when I am sending the Score. I send the score in a separate instance, where I first load the platform, user-results etc using stored IDs. 

```
$tool = LMSLTI13Controller::getLtiTool();
$tool->context = $tool->getContextById($request['contextId']);
$tool->platform = $tool->getPlatformById($request['platformId']);
$tool->resourceLink = $tool->getResourceLinkById($request['resourceLinkId']);
$tool->userResult = $tool->getUserResultById($request['userResultId']);
```

Then I use

`$ok = $tool->resourceLink->doOutcomesService(ServiceAction::Write, $outcome, $tool->userResult);`

to send the outcome to the resourceLink. However, in $http, 

```
Log::info('User Result: '.json_encode($userResult));
Log::info('LTI Outcome: '.json_encode($ltiOutcome));
$scoreService = new Service\Score($this->getPlatform(), $url);
$scoreService->submit($ltiOutcome, $userResult);
Log::info('Score Service: '.json_encode($scoreService));
$http = $scoreService->getHttpMessage();
Log::info('HTTP Response: '.$http->response);
Log::info('HTTP: '.json_encode($http));
```

I get the following response:

`HTTP: {"ok":false,"request":null,"requestHeaders":[],"response":null,"responseHeaders":[],"responseJson":null,"relativeLinks":[],"status":0,"error":"Unable to obtain an access token for scope: https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"}  `

It seems that there is an issue with the access token for the scope. The scope is defined in the lti.php (laravel):

`'lti13' => [
        'signature_method' => env('LTI13_SIGNATURE_METHOD', 'RS256'),
        'key_id' => env('LTI13_KEY_ID', 'key-1'),
        'rsa_public_key' => env('LTI13_RSA_PUBLIC_KEY'),
        'rsa_private_key' => env('LTI13_RSA_PRIVATE_KEY'),
        'auto_register_deployment_id' => env('LTI13_AUTO_REGISTER_DEPLOYMENT_ID', false),
        'required_scopes' => [
            // sample scope URLs
            //"https://purl.imsglobal.org/spec/lti-ags/scope/lineitem",
            //"https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly",
            "https://purl.imsglobal.org/spec/lti-ags/scope/score",
            //"https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly",
        ]
    ],`

I do not know what to do to get the correct token.

Do you have any way to do this?

Thanks!

**Comment by spvickers** [comment] 2024-11-07 21:21
If I understand you correctly, your issue is that Moodle is not accepting the scope you are requesting for the access token.  If this is correct, then I suggest that you check that Moodle has been configured to offer the Score service to your tool.

**Comment by onebonsai** [comment] 2024-11-15 00:38
Hi! Thanks for your answer, I went through the code with the Moodle guys. 

We see that the code goes wrong here:

```do {
            if (!$this->unsigned) {
                $accessToken = $this->platform->getAccessToken();
                if (!$this->platform->useOAuth1()) {
                    if (empty($accessToken)) {
                        $accessToken = new AccessToken($this->platform);
                        $this->platform->setAccessToken($accessToken);
                    }
                    if (!$accessToken->hasScope($this->scope)) {
                        $accessToken->get($this->scope);
                        $newToken = true;
                        if (!$accessToken->hasScope($this->scope)) {  // Try obtaining a token for just this scope
                            $accessToken->expires = time();
                            $accessToken->get($this->scope, true);
                            $retried = true;
                            if (!$accessToken->hasScope($this->scope)) {
                                if (empty($this->http)) {
                                    $this->http = new HttpMessage($url);
                                    $this->http->error = "Unable to obtain an access token for scope: {$this->scope}";
                                }
                                break;
                            }
                        }
                    }
                }
                $header = $this->platform->signServiceRequest($url, $method, $this->mediaType, $body);
            }```

`$this->http->error = "Unable to obtain an access token for scope: {$this->scope}"; `

is called. It seems that $platform->getAccessToken is not giving a result. 


The connection with Moodle is set up correctly (as far as I know). Is there any way to better understand why the accessToken is not set by the platform? The accessTokenURL is also set correctly.

It is really weird that this is going wrong. Also when I send the outcome directly in the LTI Message function, I get the same  "Unable to obtain an access token for scope" error message. 

I hope I make a bit of sense, it's been a long time I looked at this...

**Comment by spvickers** [comment] 2024-11-15 10:08
Given the response being received from Moodle, I would suggest that the code in this library is working as it should.  In my mind, the question which needs answering is why Moodle is declining to issue an access token to your tool.  It does not look like a signature issue and, If you have checked that the service has been enabled for your tool's configuration in Moodle, then it does not look like a configuration issue as I had originally suggested.  The only things I can think of to suggest next are to check the Moodle log files for clues and the Moodle code to see the conditions under which the response being sent is generated.  But, at present, I see no reason to suspect the code in this library as being the cause of your issue: it appears to be making a valid request to Moodle for an access token and receiving a valid response, just not the one you are wanting.  This still points to a configuration issue in Moodle in my mind.

**Comment by spvickers** [comment] 2024-11-18 15:33
I think trhat this library is sending the correct message to Mooidle, othwerise it would respond as it does: "Unable to obtain an access token for scope: https://purl.imsglobal.org/spec/lti-ags/scope/score".  If it did not understand the request being made it would return a very different error.  Hence my view that it is the configuration of the tool within Moodle which is causing this response.

**Comment by spvickers** [comment] 2024-11-18 15:37
If you set the library's logging level to debug you should also be able to see the request being sent to Moodle and confirm that it conforms to the required format.

**Comment by onebonsai** [comment] 2024-11-26 20:28
Thanks a lot for the help already. I have crept a small step further. Yesterday, I got the comms working, and I could send back outcomes to Moodle. There was an issue with the $request not being sent to the jwks function.

Today, however, this does not work anymore... I went again deeper, and figured out that the following function gives FALSE back:

```
public function hasScope(string $scope = ''): bool
    {
        if (str_ends_with($scope, '.readonly')) {
            $scope2 = substr($scope, 0, -9);
        } else {
            $scope2 = $scope;
        }
        Log::info('Token expires: '.$this->expires.' - '.time());
        if (!($this->expires > time())) {
            Log::info('Token expired!!!');
        }
        return !empty($this->token) && (empty($this->expires) || ($this->expires > time())) &&
            (empty($scope) || empty($this->scopes) || (in_array($scope, $this->scopes) || in_array($scope2, $this->scopes)));
    }
```
    
This is because $this->expires > time()
    
This function is in AccessToken.php and is called in ResourceLink.php under doService() function.
    
I would think that the jwks function is called to communicate the token. However, this function is never called. 

Do you have an idea why the token would expire and how to remedy it?

**Comment by onebonsai** [comment] 2024-11-26 21:36
sadly that does not seem to be the root of the issue. I did the same with a moodle installation installed on a server in the same country and there I got the same error. 

This is the log dump
```
[2024-11-26 21:17:17] production.INFO: LTI Message moodle lti1.3  
[2024-11-26 21:17:17] production.INFO: LTI Message moodle lti1.3  
[2024-11-26 21:17:17] production.INFO: {"platform":{"platformId":"https:\/\/moodle.xyz.com","clientId":"FCEzJVrBx","deploymentId":"36","authorizationServerId":null,"authenticationUrl":"https:\/\/moodle.xyz.com\/mod\/lti\/auth.php","accessTokenUrl":"https:\/\/moodle.xyz.com\/mod\/lti\/token.php","consumerName":"onebonsailms","consumerVersion":"moodle-2023042401.11","profile":null,"toolProxy":null,"consumerGuid":"bebb0c85196216ba9","cssPath":null,"protected":false,"defaultEmail":"","lastServiceRequest":null,"ok":true,"ltiVersion":"1.3.0","name":"moodle.xyz.com","secret":null,"signatureMethod":"RS256","encryptionMethod":null,"dataConnector":{},"rsaKey":"-----BEGIN PUBLIC KEY-----

MIIBIjA
1QIDAQAB

-----END PUBLIC KEY-----

","requiredScopes":[],"kid":null,"jku":"https:\/\/moodle.xyz.com\/mod\/lti\/certs.php","reason":null,"details":[],"warnings":[],"debugMode":false,"enabled":true,"enableFrom":null,"enableUntil":null,"lastAccess":1732655837,"created":1732655436,"updated":1732655812,"idScope":0},"returnUrl":null,"userResult":{"firstname":"User","middlename":"","lastname":"3","fullname":"User 3","sourcedId":"","username":null,"email":"","image":"","roles":["http:\/\/purl.imsglobal.org\/vocab\/lis\/v2\/membership#Learner"],"groups":[],"ltiUserId":"3","ltiResultSourcedId":"{\"data\":{\"instanceid\":\"31\",\"userid\":\"3\",\"typeid\":\"36\",\"launchid\":1994749385},\"hash\":\"4241a7f0a2f883d1ae29d\"}","created":1732655573,"updated":1732655837},"resourceLink":{"title":"VRFT 7","ltiResourceLinkId":"31","groupSets":null,"groups":null,"lastServiceRequest":null,"extRequest":null,"extRequestHeaders":null,"extResponse":null,"extResponseHeaders":null,"primaryResourceLinkId":null,"shareApproved":null,"created":1732655573,"updated":1732655837},"context":{"ltiContextId":"2","title":"Fire Training","type":"CourseSection","groupSets":null,"groups":null,"lastServiceRequest":null,"created":1732655573,"updated":1732655837},"defaultEmail":"","allowSharing":false,"message":null,"baseUrl":null,"vendor":{"id":null,"name":null,"description":null,"url":null,"version":null,"timestamp":null},"product":{"id":null,"name":null,"description":null,"url":null,"version":null,"timestamp":null},"requiredServices":[],"optionalServices":[],"resourceHandlers":[],"messageUrl":null,"initiateLoginUrl":null,"redirectionUris":null,"ok":true,"ltiVersion":"1.3.0","name":null,"secret":null,"signatureMethod":"RS256","encryptionMethod":null,"dataConnector":{},"rsaKey":"-----BEGIN RSA PRIVATE KEY-----
MIIEvQIBADANBgk
5b3f17+8=
-----END RSA PRIVATE KEY-----","requiredScopes":["https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"],"kid":"key-1","jku":null,"reason":null,"details":[],"warnings":[],"debugMode":false,"enabled":false,"enableFrom":null,"enableUntil":null,"lastAccess":null,"created":null,"updated":null,"idScope":0}  
[2024-11-26 21:17:17] production.INFO: {"id":3,"first_name":"Evarest","last_name":"Schoofs","pin_code":"768355","unique_id":null,"email":null,"active":0,"active_state_since":null,"avatar":null,"global_session_id":null,"lms_uid":"3","lms_active_module_code":null,"lms_updated_at":null,"extras":null,"unique_code":"6N6335ZV","unique_code_until":null,"allow_unique_code":"1","homepage":"071ff456e3748","delete_date":null,"created_at":"2024-11-25T21:05:22.000000Z","updated_at":"2024-11-25T21:05:22.000000Z","deleted_at":null,"departments":[{"id":1,"name":"General","extras":null,"created_at":"2024-03-04T10:36:08.000000Z","updated_at":"2024-03-04T10:36:08.000000Z","pivot":{"employee_id":3,"department_id":1}}]}  
[2024-11-26 21:18:42] production.INFO: tool: {"platform":{"platformId":"https:\/\/moodle.xyz.com","clientId":"FCEzJHFcUAJVrBx","deploymentId":"36","authorizationServerId":null,"authenticationUrl":"https:\/\/moodle.xyz.com\/mod\/lti\/auth.php","accessTokenUrl":"https:\/\/moodle.xyz.com\/mod\/lti\/token.php","consumerName":"onebonsailms","consumerVersion":"moodle-2023042401.11","profile":null,"toolProxy":null,"consumerGuid":"bebb0c6216ba9","cssPath":null,"protected":false,"defaultEmail":"","lastServiceRequest":null,"ok":true,"ltiVersion":"1.3.0","name":"moodle.xyz.com","secret":null,"signatureMethod":"RS256","encryptionMethod":null,"dataConnector":{},"rsaKey":"-----BEGIN PUBLIC KEY-----\r\nMIIBNeh7i\r\n1QIDAQAB\r\n-----END PUBLIC KEY-----\r\n","requiredScopes":[],"kid":null,"jku":"https:\/\/moodle.xyz.com\/mod\/lti\/certs.php","reason":null,"details":[],"warnings":[],"debugMode":false,"enabled":true,"enableFrom":null,"enableUntil":null,"lastAccess":1732579200,"created":1732655436,"updated":1732655812,"idScope":0},"returnUrl":null,"userResult":{"firstname":"","middlename":"","lastname":"","fullname":"","sourcedId":null,"username":null,"email":"","image":"","roles":[],"groups":[],"ltiUserId":"3","ltiResultSourcedId":"{\"data\":{\"instanceid\":\"31\",\"userid\":\"3\",\"typeid\":\"36\",\"launchid\":1994749385},\"hash\":\"4241a7f0a3d1ae29d\"}","created":1732655573,"updated":1732655837},"resourceLink":{"title":"VRFT 7","ltiResourceLinkId":"31","groupSets":null,"groups":null,"lastServiceRequest":null,"extRequest":null,"extRequestHeaders":null,"extResponse":null,"extResponseHeaders":null,"primaryResourceLinkId":null,"shareApproved":null,"created":1732655573,"updated":1732655837},"context":{"ltiContextId":"2","title":"Fire Training","type":"CourseSection","groupSets":null,"groups":null,"lastServiceRequest":null,"created":1732655573,"updated":1732655837},"defaultEmail":"","allowSharing":false,"message":null,"baseUrl":null,"vendor":{"id":null,"name":null,"description":null,"url":null,"version":null,"timestamp":null},"product":{"id":null,"name":null,"description":null,"url":null,"version":null,"timestamp":null},"requiredServices":[],"optionalServices":[],"resourceHandlers":[],"messageUrl":null,"initiateLoginUrl":null,"redirectionUris":null,"ok":true,"ltiVersion":null,"name":null,"secret":null,"signatureMethod":"RS256","encryptionMethod":null,"dataConnector":{},"rsaKey":"457a05e271509788","requiredScopes":["https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"],"kid":"key-1","jku":null,"reason":null,"details":[],"warnings":[],"debugMode":false,"enabled":false,"enableFrom":null,"enableUntil":null,"lastAccess":null,"created":null,"updated":null,"idScope":0}  
[2024-11-26 21:18:42] production.INFO: AGS: https://moodle.xyz.com/mod/lti/services.php/2/lineitems/33/lineitem?type_id=36  
[2024-11-26 21:18:42] production.INFO: Not empty AGS  
[2024-11-26 21:18:42] production.INFO: Do Score Service: https://moodle.xyz.com/mod/lti/services.php/2/lineitems/33/lineitem?type_id=36  
[2024-11-26 21:18:42] production.INFO: User Result: {"firstname":"","middlename":"","lastname":"","fullname":"","sourcedId":null,"username":null,"email":"","image":"","roles":[],"groups":[],"ltiUserId":"3","ltiResultSourcedId":"{\"data\":{\"instanceid\":\"31\",\"userid\":\"3\",\"typeid\":\"36\",\"launchid\":1994749385},\"hash\":\"4241a7f0a2f897d438a3d1ae29d\"}","created":1732655573,"updated":1732655837}  
[2024-11-26 21:18:42] production.INFO: LTI Outcome: {"language":"en-US","status":null,"date":"2024-11-26T21:18:42Z","type":"decimal","activityProgress":"Submitted","gradingProgress":"NotReady","comment":"","submissionStarted":null,"submissionCompleted":null,"dataSource":null,"ltiUserId":null}  
[2024-11-26 21:18:42] production.INFO: SENDING INFO  
[2024-11-26 21:18:42] production.INFO: accessToken:   
[2024-11-26 21:18:42] production.INFO: accessToken 2: {"token":null,"expires":null,"scopes":[],"created":null,"updated":null}  
[2024-11-26 21:18:42] production.INFO: Token expires:  - 1732655922  
[2024-11-26 21:18:42] production.INFO: Token expired!!!  
[2024-11-26 21:18:42] production.INFO: hasScope 1  
[2024-11-26 21:18:42] production.INFO: Token expires:  - 1732655922  
[2024-11-26 21:18:42] production.INFO: Token expired!!!  
[2024-11-26 21:18:42] production.INFO: hasScope 2  
[2024-11-26 21:18:42] production.INFO: Token expires: 1732655922 - 1732655922  
[2024-11-26 21:18:42] production.INFO: Token expired!!!  
[2024-11-26 21:18:42] production.INFO: HTTP OUT: {"ok":false,"request":null,"requestHeaders":[],"response":null,"responseHeaders":[],"responseJson":null,"relativeLinks":[],"status":0,"error":"Unable to obtain an access token for scope: https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"}  
[2024-11-26 21:18:42] production.INFO: Score Service: {"unsigned":false}  
[2024-11-26 21:18:42] production.INFO: HTTP Response:   
[2024-11-26 21:18:42] production.INFO: HTTP: {"ok":false,"request":null,"requestHeaders":[],"response":null,"responseHeaders":[],"responseJson":null,"relativeLinks":[],"status":0,"error":"Unable to obtain an access token for scope: https:\/\/purl.imsglobal.org\/spec\/lti-ags\/scope\/score"}  
[2024-11-26 21:18:42] production.INFO: Token expires: 1732655922 - 1732655922  
[2024-11-26 21:18:42] production.INFO: Token expired!!!  
[2024-11-26 21:18:42] production.INFO: Token expires: 1732655922 - 1732655922  
[2024-11-26 21:18:42] production.INFO: Token expired!!!  
[2024-11-26 21:18:42] production.INFO: Result failed to sent to LMS: {"language":"en-US","status":null,"date":"2024-11-26T21:18:42Z","type":"decimal","activityProgress":"Submitted","gradingProgress":"NotReady","comment":"","submissionStarted":null,"submissionCompleted":null,"dataSource":null,"ltiUserId":null}  

```
I removed the private data. 

The log shows that the token does not exist and is created. 

I went a bit deeper and extracted the error message from the $http->send function

```
[2024-11-26 21:31:21] production.INFO: Http\HttpMessage->send POST request to 'https://moodle.onebonsai.com/mod/lti/token.php'
POST /mod/lti/token.php HTTP/2
Host: moodle.onebonsai.com
accept: application/json
content-type: application/x-www-form-urlencoded; charset=UTF-8
content-length: 0
Response:
HTTP/2 400 
server: nginx-rc
date: Tue, 26 Nov 2024 21:31:21 GMT
content-type: text/html; charset=utf-8

{
  "error" : "invalid_request"
}  
```

This function is called in

`public function get(string $scope = '', bool $scopeOnly = false): AccessToken`

in AccessToken. 

It seems that somehow the token retrieval is not working...

**Comment by spvickers** [comment] 2024-11-26 21:41
You seem to be back to the original issue ("Unable to obtain an access token for scope: https://purl.imsglobal.org/spec/lti-ags/scope/score") which I believe is caused by the Moodle configuration for your tool.

**Comment by onebonsai** [comment] 2024-11-27 19:51
It is weird, as I created a separate Laravel site and there it does work. So somewhere in my code of the real site something is going wrong. It's frustrating as you can imagine :-)

I'll struggle on, hopefully will find it eventually.

Thanks!

**Comment by onebonsai** [comment] 2024-11-27 20:26
Actually, it might be a server issue on the Moodle end. I found an old post 

https://devforum.zoom.us/t/access-token-is-expired-for-the-zoom-setup-at-moodle/33300/10

talking about some kind of clock setup on Moodle. It apparently does not sync well ?...

I managed to make it work on my own Moodle setup, and it works all fine. Go figure :-)

Hope they can figure it out on the Moodle side, and we're finally out of this hell!

Thanks again for the support both moral as technical!

**Comment by spvickers** [comment] 2024-11-29 14:17
Glad that I could help a little.  As none of the problems you encountered appears to have been caused by the code in the repo, I will close this issue.  If you later find this code is causing an error, please open a new issue to report it.

**Closed by spvickers** 2024-11-29 14:17 UTC
