### ISSUE TITLE
Unable to verify JWT signature

### ISSUE THREAD

**Issue by kggayo** [celtic-project/LTI-PHP#43] opened 2023-02-03 09:51 UTC
I have a problem calling the Access token service. The service will return "Unable to verify JWT signature".

This is my JWT:
```eyJhbGciOiJSUzI1NiIsImtpZCI6InhFQU92ZlRVeS1HaExKUVdIWldDZG43MGt5cEM1cmhVQkw4SmVJcEs0WE0iLCJ0eXAiOiJKV1QiLCJjdHkiOiJKV1QifQ.eyJpc3MiOiIxIiwic3ViIjoiMSIsImF1ZCI6Imh0dHBzOi8vc2FsdGlyZS5sdGkuYXBwL3BsYXRmb3JtL3Rva2VuLzcxY2Y0YjQyMmNhYmViMzEwMzNmZjIxMTgzZjUxMDJjIiwiaWF0IjoiMTY3NTQxNzUxMSIsIm5iZiI6IjE2NzU0MTc1MDYiLCJleHAiOiIxNjc1NDE3ODExIiwianRpIjoiU1ptRzFOQlluNHpMV3luUVFPVklBVUt0S2EzSjgyZ2ZVV2d5MEdycE5YUT0ifQ.rCcabTs7G0rn7QldvDexhd5YLBnmrr8-VwxZeOrpGKYgNIWSIoaB0toJ1nRN-fHd3Xw_FDs2s1OOXngadXiX1nhO6JUDwKcS4_NjFzWqijj8jSrTHIMulz_wJMQ6z-IfTF71DojxspIy4O8WLFtREKurBcIdxmFfImP54PD6PKFy85p8Fc5_kRe-rQ067ZW5Ym1CPReUNz26MDvQnGEX13o1YwtT7payclx_5FdYNI7I69U5VoyM576CHQAFQIn0W0WchIV4_k7_BH8V1evlYe2WkZAwqnSWCarne-P9zj2Itw4WBtDH2f7BRjO3Veiv-1Kr1_4IyzmDzLrKrsR1cg```

And here is my public key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKcalKthx1myIpklYH4j
9uQcmgQuZtKO4/beqK17QN3E4X3B/TIfX9twr0Uj3VuV7XNyh0SJxTNMnxzITCD3
807D/SBOAqn+y6GlBRK1BKloeioK58IRXR+fygbFAeOf+TTrBkQpNm/XOIS64U9t
479WZ+xILRvbfiUVc6hCIPUl8UkQ6Jdjm+v1CJk7Mh1IlIAcqrXqq5NG8xEY7HWM
7xRdX1A/KJlVBY03F86q/kTMrTPHBaChd3Egtdle/qKg9RKoCI4DTDV0f89+NT5y
YjJo8zJ2rNSmIr4Pf8nfQt1qDq48J5SsS4znEUuoqUSyBGgUAP5y2CP3U8Hoh8SZ
lQIDAQAB
-----END PUBLIC KEY-----

I verified the token in JWT.io and it was able to verify the signature. And I also tried the same application against Moodle and [https://lti-ri.imsglobal.org](https://lti-ri.imsglobal.org/platforms/3579). It was able to get the access token.

**Comment by spvickers** [comment] 2023-02-03 10:04
What method are you using to make the request to the access token endpoint?  Are you using the Access Token service directly, or using one of the other services to make it for you?  What are the other parameters you are sending with the client_assertion JWT in case the error message is misleading?

**Comment by spvickers** [comment] 2023-02-03 10:06
Is your public key endpoint publicly available and using a non-self-signed SSL certificate?

**Comment by spvickers** [comment] 2023-02-03 10:09
If your code is working against some LTI platforms, what is making you think the issue is with this library and not the platform you are using?

**Comment by spvickers** [comment] 2023-02-03 10:33
Looking at your JWT I notice that the iat, exp or nbf claims are string rather than integer values.  This could be the cause of your issue.

**Comment by spvickers** [comment] 2023-02-05 18:46
I have not been able to find anything in this code which would have generated the JWT you quote, so believe that you are not using this library for generating your service requests.  I am, therefore, closing this issue.  If I am incorrect and the error is being caused by this library, please re-open the issue with more details.  Thanks.

**Closed by spvickers** 2023-02-05 18:46 UTC

**Comment by spvickers** [comment] 2023-02-06 08:17
No, this repository is for the LTI PHP library.  For help with saLTIre please use the Feedback option from the Help button.

**Comment by kggayo** [comment] 2023-02-06 08:20
Oh! Sorry for your time. 
I'm barking at the wrong tree.
